services:
  #ollama:
  #  volumes:
  #    - ollama:/root/.ollama
  #  container_name: ollama
  #  pull_policy: always
  #  tty: true
  #  restart: unless-stopped
  #  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./config/open-webui:/app/backend/data
    #depends_on:
    #  - ollama
    ports:
      - 8992:8080
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.0.18:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`ai.${hostname}`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls.certresolver=myresolver"
    restart: unless-stopped